# Generated by Django 3.0.8 on 2020-07-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
