# Generated by Django 3.0.8 on 2020-07-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20200729_1759'),
        ('community', '0006_auto_20200728_2109'),
    ]

    operations = [
    ]
