# Generated by Django 3.0.8 on 2021-05-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20200730_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='isi_konten',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='judul',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_image',
            new_name='upload_gambar',
        ),
    ]
