# Generated by Django 3.0.8 on 2021-04-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_class', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftar_pre_toefl',
            name='message',
            field=models.CharField(default='Saya telah mendaftar kelas', max_length=2000),
        ),
    ]
