# Generated by Django 3.0.8 on 2021-04-07 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_class', '0002_daftar_pre_toefl_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='daftar_english_todler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=30, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^(\\+\\d{1,3})?,?\\s?\\d{8,13}')])),
            ],
        ),
        migrations.RemoveField(
            model_name='daftar_pre_toefl',
            name='message',
        ),
    ]
